version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: vijaya294/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql    [mysql stores data in /bar/lib/mysql/]
  backend:
    image: vijaya294/backend:v1
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: vijaya294/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend

































